export const DIVINE_QUOTES = [
  // Lord Shiva
  "Shiva teaches that true power comes from inner silence.",
  "Destroy your ego, not your dreams.",
  "The calmest mind holds the greatest strength.",
  "Like Shiva, remain steady amidst life's storms.",
  "Meditation is the path to the Mahadev within.",
  "What must end, let it end; what must begin, welcome it.",
  "Fear disappears where faith in Shiva begins.",
  "Mahadev transforms poison into wisdom.",
  "Detachment is not weakness; it is freedom.",
  "The third eye opens when ignorance closes.",
  "Shiva reminds us that simplicity is divine.",
  "Every ending is the beginning of a higher journey.",
  "Conquer yourself before conquering the world.",
  "In stillness, Shiva speaks.",
  "The strongest soul is the one at peace.",
  "Let go of anger and embrace awareness.",
  "Mahadev's greatest weapon is self-mastery.",
  "Darkness fades before the light of consciousness.",
  "A disciplined mind is Shiva's true temple.",
  "When the world shakes, stand firm like Kailash.",
  // Lord Rama
  "Dharma is doing what is right even when it is difficult.",
  "Character is a person's greatest wealth.",
  "Lord Rama teaches that duty comes before comfort.",
  "Truth always finds its way to victory.",
  "A noble heart wins battles before weapons do.",
  "Honor every promise you make.",
  "Leadership begins with self-discipline.",
  "Walk the path of righteousness without fear.",
  "Patience and virtue create lasting success.",
  "Rama's life proves that goodness is strength.",
  "Respect earned through actions lasts forever.",
  "Every challenge is a test of character.",
  "Justice without compassion is incomplete.",
  "Let your actions speak louder than your words.",
  "Loyalty is the foundation of trust.",
  "The path of truth may be long, but it never fails.",
  "Serve others with humility and grace.",
  "Greatness comes from integrity, not power.",
  "Victory belongs to those who uphold dharma.",
  "Be the reason someone believes in goodness.",
  // Lord Hanuman
  "Faith turns the impossible into possible.",
  "Strength is meaningful only when used for good.",
  "Hanuman teaches courage without arrogance.",
  "Devotion gives wings to determination.",
  "No mountain is too high for unwavering faith.",
  "Humility and power can coexist.",
  "The greatest servant becomes the greatest hero.",
  "Fear disappears when devotion grows.",
  "Hanuman's secret strength was believing in his purpose.",
  "True confidence comes from selfless service.",
  "Every obstacle bows before perseverance.",
  "Loyalty is the mark of a noble soul.",
  "The strongest heart is filled with devotion.",
  "Remember your strength when doubt appears.",
  "Faith fuels extraordinary achievements.",
  "Dedication transforms effort into miracles.",
  "Hanuman teaches action over excuses.",
  "A pure heart is stronger than any weapon.",
  "Serve with sincerity and success will follow.",
  "Courage begins where fear ends.",
  // Goddess Durga
  "Strength and compassion can walk together.",
  "Every woman carries a spark of Durga within.",
  "Courage is the first step toward victory.",
  "Durga reminds us to rise after every fall.",
  "Protect your peace with fearless determination.",
  "Evil cannot survive where truth stands strong.",
  "Confidence is divine energy in action.",
  "Face challenges like a warrior, not a victim.",
  "Durga teaches strength with wisdom.",
  "The brave heart always finds a way.",
  "Never underestimate the power of resilience.",
  "Inner strength shines brighter than outer beauty.",
  "Victory belongs to those who refuse to surrender.",
  "Fear is temporary; courage is eternal.",
  "Empower yourself and inspire others.",
  "The goddess within awakens through self-belief.",
  "Difficult battles reveal hidden strength.",
  "Stand tall, even when the world doubts you.",
  "Durga's blessing is courage in every step.",
  "A fearless spirit can change destiny.",
  // Lord Krishna
  "Focus on your actions, not the outcome.",
  "A joyful heart is Krishna's greatest gift.",
  "Wisdom begins where attachment ends.",
  "Life is a dance; learn to move with grace.",
  "Krishna teaches balance in every situation.",
  "Happiness grows when shared with others.",
  "The soul is eternal; fear is temporary.",
  "Every challenge carries a hidden lesson.",
  "Act with sincerity and leave the rest to destiny.",
  "Love without conditions and live without regrets.",
  "Krishna's flute reminds us to stay in harmony.",
  "Peace comes from understanding your true self.",
  "Do your best and let God handle the rest.",
  "Every moment is an opportunity to grow.",
  "The strongest victory is over your own mind.",
  "Compassion makes life meaningful.",
  "Trust the journey even when you cannot see the path.",
  "Joy is found in the present moment.",
  "Krishna teaches wisdom through simplicity.",
  "The heart that loves selflessly never loses.",
  // Lord Ganesha
  "Every new beginning starts with Ganesha's blessings.",
  "Obstacles are opportunities in disguise.",
  "Wisdom is greater than strength.",
  "Ganesha teaches us to think before we act.",
  "Patience opens doors that force cannot.",
  "Success follows preparation and persistence.",
  "Learn continuously and grow endlessly.",
  "A calm mind solves difficult problems.",
  "Remove negativity before seeking progress.",
  "The best solutions come from clear thinking.",
  "Ganesha's wisdom turns confusion into clarity.",
  "Start small, dream big, and stay consistent.",
  "Every obstacle teaches a valuable lesson.",
  "Listen more than you speak.",
  "Intelligence shines brightest with humility.",
  "A positive attitude attracts positive outcomes.",
  "Growth begins when fear ends.",
  "Wisdom guides where strength cannot.",
  "Trust the process and keep moving forward.",
  "Every step taken with faith brings success closer."
];
